### ISSUE TITLE
 undefined symbol: gzclose

### ISSUE THREAD

**Issue by simonjuleseric2** [nanoporetech/minimappy#1]
After trying to install minimappy following the instructions, I get the following error:

OSError: cannot load library '/home/simon/anaconda3/envs/simenv/lib/python3.7/site-packages/minimappy-0.1.0-py3.7-linux-x86_64.egg/minimaplib.cpython-37m-x86_64-linux-gnu.so': /home/simon/anaconda3/envs/simenv/lib/python3.7/site-packages/minimappy-0.1.0-py3.7-linux-x86_64.egg/minimaplib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: gzclose

Apparently the zlib library is missing, any idea how to correct it?

**Comment by cjw85** [comment]
Hi @simonjuleseric2,

Can I ask why you are trying to use minimappy? As [noted](https://github.com/jupyterlab/extension-examples) in the README, this library was deprecated when [mappy](https://pypi.org/project/mappy/) was made available.

**Comment by simonjuleseric2** [comment]
Sorry, my bad is there an example of simple sequence alignment using mappy?

**Comment by cjw85** [comment]
The documentation for mappy would be a good place to start.

**Comment by simonjuleseric2** [comment]
Yes indeed but the details in the documentation are rather limited. For exemple it says that alignement is done relative to an index, where is that index defined. We can also not directly align sequence from str but from Aligner, how do we define those?

**Comment by simonjuleseric2** [comment]
The minimappy had some concrete exemples (https://nanoporetech.github.io/minimappy/) but I couldn't find the same from mappy

**Comment by cjw85** [comment]
The link I provided above to mappy contained exactly analogous examples. For further help with mappy please ask questions on the appropriate github repository.
